### PR TITLE
bug: fix invalid version numbers

### PR DESCRIPTION
**Pull request by dopiera**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/70)

### CODE REVIEW

**Comment by tmatsuo** [comment]
Yeah, probably it's better to update the version at:
https://github.com/googleapis/google-cloud-cpp-common/blob/f933fc580d5f5f8abf1d270dd15ea07c07aef600/google/cloud/grpc_utils/CMakeLists.txt#L19

**Comment by dopiera** [comment]
For some reason github is preventing me from force pushing to my branch anymore. Closing this PR and opening a new one: https://github.com/googleapis/google-cloud-cpp-common/pull/71/

**Comment by tmatsuo** [comment]
@coryan Ah, yes, if there's no change, LGTM with the same version. @dopiera Sorry for confusion

**Comment by coryan** [comment]
I think Kokoro might be confused by the opening and closing of this PR.  Not sure, but  I cannot explain why it is "hung" otherwise.

**Comment by dopiera** [comment]
I tried pushing new code, it didn't help, so I opened #74 .

**Pull request closed without merging**
