### PR TITLE
feat: implement std::apply

### PR DESCRIPTION
**Pull request by dopiera**
This is a part of googleapis/google-cloud-cpp#3016.

Composing GCS objects consists of multiple operations under the hood.
Different subsets of the options passed to the recursive compose
operation have to be passed on to the underlying operations.

By GCS C++ client convention, options are passed as parameter packs,
hence in the general case the filtering has to be done in compile time.

An easy way to filter these parameters is to pack them in a
`std::tuple`, process the tuple and apply it via `std::apply`.
Unfortunately, `std::apply` is only available in C++14, so this PR
reimplements it in a API-compatible way.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/59)

### CODE REVIEW

**Comment by dopiera** [comment]
I'm afraid the kokoro failures are permissions problems to GCR. @coryan would you mind taking a look?

This is what I'm getting in the kokoro builds:
```
Error response from daemon: Get https://gcr.io/v2/cloud-cpp-reserved/google-cloud-cpp-common/test-install-debian-stretch/manifests/latest: denied: Token exchange failed for project 'cloud-cpp-reserved'. Please enable or contact project owners to enable the Google Container Registry API in Cloud Console at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?project=cloud-cpp-reserved before performing this operation.
```

**Comment by dopiera** [comment]
Hmm, some succeeded. I'm also seeing `received unexpected HTTP status: 503 Service Unavailable` so maybe I'll just retry.

**Comment by coryan** [comment]
I think there are larger problems with the Kokoro builds right now.  The google-cloud-cpp builds also broke at the same time.
/cc: @devbww FYI.

**Comment by devbww** [comment]
Yeah.  I see ...
```
received unexpected HTTP status: 503 Service Unavailable
```

**Pull request merged**
